spring:
  application:
    name: homecare
  datasource:
    url: 'jdbc:mysql://localhost:3308/homecare'
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: true
        show:
          sql: true
        format_sql: true
        hb2dll:
          auto: update
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE